services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      PG_DATA: /data/postgres
    volumes:
      - storage:/data/postgres
    ports:
      - "5432:5432"

  application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
      CORS_ALLOWED_METHODS: "${CORS_ALLOWED_METHODS}"
      OAUTH_ISSUER_URI: "${OAUTH_ISSUER_URI}"
volumes:
  storage:
