version: '3.1'

services:
  db:
    image: postgres
    container_name: smtm_api_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      PG_DATA: /data/postgres
    volumes:
      - storage:/data/postgres
    ports:
      - "5432:5432"
volumes:
  storage: