CREATE TABLE CATEGORY_SETS (
    OWNER_ID BIGINT PRIMARY KEY,
    VERSION INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE CATEGORIES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OWNER_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ICON VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX UQ_CATEGORIES_OWNER_ID_NAME ON CATEGORIES (NAME);

ALTER TABLE CATEGORIES
    ADD CONSTRAINT FK_CATEGORIES_CATEGORY_SETS
    FOREIGN KEY (OWNER_ID)
    REFERENCES CATEGORY_SETS (OWNER_ID)
    ON DELETE CASCADE;