@startuml

component Security
interface UserRegistration
interface CredentialsAuthentication
interface RefreshTokenAuthentication
interface Authorization
interface UsersRepository

package "Infrastructure" {
    rectangle UsersRepositoryAdapter <<database>>
    UsersRepositoryAdapter -down-( UsersRepository
}

Security -up- UsersRepository
Security -down- UserRegistration
Security -down- CredentialsAuthentication
Security -down- RefreshTokenAuthentication
Security -down- Authorization

package "Application" {
    rectangle UsersController <<resource>>
    rectangle TokensController <<resource>>
    rectangle JwtAuthorizationFilter <<filter>>
    JwtAuthorizationFilter -up-> Authorization
    TokensController -up->CredentialsAuthentication
    TokensController -up->RefreshTokenAuthentication
    UsersController -up-> UserRegistration
}

@enduml
