@startuml

component Categories
interface CategoryRegister
interface CategoriesRepository

package "Infrastructure" {
    rectangle CategoriesRepositoryAdapter <<database>>
    CategoriesRepositoryAdapter -down-( CategoriesRepository
}

Categories -up- CategoriesRepository
Categories -down- CategoryRegister

package "Application" {
    rectangle CategoriesController <<resource>>
    CategoriesController -up-> CategoryRegister
}

@enduml
